#!/bin/sh

myip=$(/sbin/ifconfig eth0 | grep "inet " | sed 's/  */ /g' | cut -d' ' -f3)
iprange="$(echo $myip | sed 's/\.[0-9]*$/\.\*/g')"
nmap -sn $iprange | grep -Eo '([0-9][0-9.]+$)' | grep -v "$(echo $myip | sed 's/\./\\\./g')$" > $HOME/bin/hostiplist
for i in $(<$HOME/bin/hostiplist); do ssh $i hostname; done > $HOME/bin/hostlist

sshin=$(cat $HOME/bin/hostlist | wc -l)
ipcount=$(cat $HOME/bin/hostiplist | wc -l)

if [ $sshin -eq $ipcount ]; then
  status="OK"
else
  status="KO"
fi

echo "status=$status;hosts=$ipcount;sshin=$sshin"
