#!/bin/sh

myip=$(/sbin/ifconfig eth0 | sed -n 's/ *inet [^0-9]*\([0-9\.]\+\).*/\1/p')
iprange=${myip%.*}.*
nmap -sn $iprange | grep -Eo '([0-9][0-9.]+$)' | grep -v "^$myip$" > $HOME/bin/hostiplist
for i in $(<$HOME/bin/hostiplist); do ssh $i hostname; done > $HOME/bin/hostlist

echo "Found $(wc -l $HOME/bin/hostlist) hosts."
